### ISSUE TITLE
TODO : use isset()

### ISSUE THREAD

**Issue by agussuroyo** [weuwman/ss-wp-assessment#2]
bisa tolong diperbaiki menggunakan isset, sebelum pemanggilan value dari varibale $_GET

<img width="379" alt="screen shot 2018-03-27 at 16 44 41" src="https://user-images.githubusercontent.com/5734710/37959848-4cdc675c-31de-11e8-80ae-a7285f64cb21.png">

**Comment by weuwman** [comment]
Done
