### ISSUE TITLE
TODO : use wp_mail

### ISSUE THREAD

**Issue by agussuroyo** [weuwman/ss-wp-assessment#3]
bisa tolong ubah menggunakan wp_mail()?

<img width="494" alt="screen shot 2018-03-27 at 16 46 00" src="https://user-images.githubusercontent.com/5734710/37959900-6ac8e7a4-31de-11e8-9583-7cced42493e2.png">

https://developer.wordpress.org/reference/functions/wp_mail/

**Comment by weuwman** [comment]
Done
